### ISSUE TITLE
eval_chem error ' Each row of output must be identified by a unique combination of keys'

### ISSUE THREAD

**Issue by w-jan** [inbo/watina#22]
When I run this code, I get this error-message, even with a unique row-id

```r
library (watina)
watina <- connect_watina()

tubes <- get_locs(watina,
                  buffer = 10, loc_type = "P", loc_validity = c("VLD", "ENT"), collect = TRUE)
tubes_chem <- get_chem(tubes,watina,"1/1/2015", conc_type = "mass", collect= TRUE, strict_en = FALSE) 

mystats <- eval_chem(tubes_chem, chem_var = c("N-NO3", "P-PO4"))
tubes_chem <- tibble::rowid_to_column(tubes_chem)
mystats <- eval_chem(tubes_chem, chem_var = c("N-NO3", "P-PO4"))
```

**Comment by w-jan** [comment]
I edited the initial issue, because the code wasn't reproducible.

**Comment by florisvdh** [comment]
It has to do with the occurrence of multiple measurements of a chemical variable for a single water sample. This occurs for 5 water samples in the whole database (period 2016-2017-2018). Before being able to adapt the implementation, it has to be clarified what to do with these double measurements, which clearly can differ a lot. If only one of them is right: how to distinguish it? Or should this be taken care of in the database?

**Comment by florisvdh** [comment]
After discussion with @mathiaswackenier it appears that these multiple measurements should not have been present in the database. It will be solved soon within the datawarehouse.
