### ISSUE TITLE
error get_locs()

### ISSUE THREAD

**Issue by w-jan** [inbo/watina#5]
get_locs(watina, mask = habmap_polygons_gw, join_mask = TRUE, buffer = 10, loc_type = "P", loc_validity = c("VLD", "ENT"), collect = TRUE)  raises following error:
Error: <SQL> 'SELECT COUNT(*) AS "n"
FROM (SELECT *
FROM (SELECT DISTINCT *
FROM (SELECT "MeetpuntWID" AS "loc_wid", "MeetpuntCode" AS "loc_code", "GebiedCode" AS "area_code", "GebiedNaam" AS "area_name", "MeetpuntXCoordinaat" AS "x", "MeetpuntYCoordinaat" AS "y", "MeetpuntStatusCode" AS "loc_validitycode", "MeetpuntStatus" AS "loc_validity", "MeetpuntTypeCode" AS "loc_typecode", "MeetpuntType" AS "loc_typename"
FROM (SELECT *
FROM (SELECT "LHS"."MeetpuntWID" AS "MeetpuntWID", "LHS"."MeetpuntID" AS "MeetpuntID", "LHS"."MeetpuntCode" AS "MeetpuntCode", "LHS"."GebiedWID" AS "GebiedWID", "LHS"."MeetpuntStatusCode" AS "MeetpuntStatusCode", "LHS"."MeetpuntStatus" AS "MeetpuntStatus", "LHS"."MeetpuntTypeCode" AS "MeetpuntTypeCode", "LHS"."MeetpuntType" AS "MeetpuntType", "LHS"."MeetpuntXCoordinaat" AS "MeetpuntXCoordinaat", "LHS"."MeetpuntYCoordinaat" AS "MeetpuntYCoordinaat", "LHS"."GebiedCode" AS "GebiedCode", "LHS"."GebiedNaam" AS "GebiedNaam", "RHS"."PeilpuntStatusCode" AS "PeilpuntStat
In addition: Warning messages:
1: `chr_along()` is deprecated as of rlang 0.2.0.
This warning is displayed once per session. 
2: `overscope_eval_next()` is deprecated as of rlang 0.2.0.
Please use `eval_tidy()` with a data mask instead.
This warning is displayed once per session. 

To reproduce the mask-object:

habpath <- "./data/local/n2khab-binaire-databronnen"
habfile <- "20_processed/habitatmap_stdized/habitatmap_stdized.gpkg"

habmap_polygons <- st_read(file.path(habpath, habfile),
                           "habitatmap_polygons",
                           quiet = TRUE)
habmap_polygons <- habmap_polygons %>%
    mutate( description_orig = as.character( .data$description_orig)) %>%
    st_transform(31370)
habmap_patches <- suppressWarnings(
    st_read(file.path(habpath, habfile),
            "habitatmap_patches",
            as_tibble = TRUE,
            quiet = TRUE)
    )
types <- suppressWarnings(read_types(path = "../n2khab/inst/textdata", lang = "nl"))

habmap_patches <- habmap_patches %>%
    mutate( polygon_id = as.factor(.data$polygon_id),
            patch_id = as.numeric(.data$patch_id),
            certain = .data$certain == 1,
            type = factor(.data$type,
                          levels = levels(types$type)
                          )
            )

gw_types <- read_scheme_types(path = "../n2khab/inst/textdata") %>%
    filter(scheme == "GW_05.1_terr") %>%
    arrange(typegroup) %>%
    mutate(groupnr = as.integer(str_sub(typegroup, -1))) %>% 
    select(type, groupnr)

habmap_patches_gw <- habmap_patches %>% 
  inner_join(gw_types, by = c("type" = "type"))
habmap_polygons_gw <- habmap_polygons %>% 
  inner_join(habmap_patches_gw %>% select(-code_orig), by = "polygon_id")

greetings,
Jan

**Comment by florisvdh** [comment]
It appears that the SQL Server error gets truncated. Can you give below code a try? I adapted your code in order to use the `n2khab` functions, but it probably should not make a difference. Anyway, it works here.

If the problem persists, it may still have to do with your installed package versions: then please return your output of `devtools::session_info()`, or first update all R packages and try again. I don't get the `rlang` warnings, this [may indicate](https://github.com/r-lib/rlang/issues/674) version conflicts. I am currently using `dplyr` version 0.8.3.

Further, you can check whether the problem persists when fewer arguments are given, in order to track down the source of the problem. (Note that your settings for `buffer` and `loc_type` are the default, so they can be discarded if you like.)

A starting point to test the function is `example(get_locs, run.dontrun = TRUE)`.

```r
datapath <- "data" # adapt to your local setup
library(n2khab)
library(tidyverse)
library(sf)
library(watina)
habitatmap_stdized <- read_habitatmap_stdized(datapath)
habmap_polygons <- habitatmap_stdized$habitatmap_polygons
habmap_patches <- habitatmap_stdized$habitatmap_patches
watina <- connect_watina()

gw_types <- 
    read_scheme_types() %>%
    filter(scheme == "GW_05.1_terr") %>%
    arrange(typegroup) %>%
    mutate(groupnr = as.integer(str_sub(typegroup, -1))) %>%
    select(type, groupnr)

habmap_patches_gw <- 
    habmap_patches %>%
    inner_join(gw_types, by = c("type" = "type"))

habmap_polygons_gw <- habmap_polygons %>%
    inner_join(habmap_patches_gw %>% select(-code_orig), by = "polygon_id")
# as a consequence, the result contains many duplicate polygons, but
# maybe that was intended. 7914 features are present two or more times:
    habmap_polygons_gw %>% 
        st_drop_geometry() %>% 
        count(polygon_id) %>% 
        filter(n > 1)

mylocs <- 
    get_locs(watina, 
             mask = habmap_polygons_gw, 
             join_mask = TRUE, 
             buffer = 10,
             loc_type = "P",
             loc_validity = c("VLD", "ENT"), 
             collect = TRUE)
# Works fine here.

# An alternative, avoiding the inflation of habmap_polygons_gw:

    habmap_polygons_gw <- habmap_polygons %>%
        semi_join(habmap_patches_gw, by = "polygon_id")
    
    mylocs_2 <- 
        get_locs(watina, 
                 mask = habmap_polygons_gw, 
                 join_mask = TRUE, 
                 buffer = 10,
                 loc_type = "P",
                 loc_validity = c("VLD", "ENT"), 
                 collect = TRUE) %>% 
        inner_join(habmap_patches_gw %>% 
                       select(-code_orig), 
                   by = "polygon_id")

all.equal(mylocs, mylocs_2) # TRUE
nrow(mylocs_2) # 6012
```

**Comment by w-jan** [comment]
I still encounter problems with get_locs(). Unfortunately there's one more.
Today the select-function doesn't work any more. I've to make it explicit dplyr::select to let it work.
The basic problem in this issue still exists. Everything goes right until line 264 (get_locs-function): nr_dropped_locs. The filtering and counts arises errors. It seems to me that de sql-statement became too complex ? I can only bypass it by collecting the loc's before making the nr_dropped_locs-object.
We've the same dplyr-version.

**Comment by florisvdh** [comment]
Regarding your problem with `get_locs()`:

1. do you have the same problems when running the function's examples?
1. what is your **dbplyr** version? Mine is 1.4.2.

Regarding `dplyr::select()`, I suspect this is the conflict with `raster::select()`, in an R script. That can be prevented by first loading raster and then tidyverse in an R-script:

```r
library(raster)
library(sf)
library(tidyverse)
# other library-statements can come here or earlier
# rest of your script
```

However, you should not encounter select-conflicts when directly applying `get_locs()` from the n2khab-package, as it always uses `dplyr::select()`. But I understand that it does not work yet ;-).

To debug `get_locs()`, you better run `debugonce(get_locs)`, then run your `get_locs()` statement. See more info [here](https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio). You can then run the function step by step (or specific parts of it, by hand) without the need to copy its code elsewhere. This avoids some possible effects from your R-script, such as the select-trouble.

**Comment by w-jan** [comment]
Also the second example : get_locs(watina,
         area_codes = c("KAL", "KBR"),
         collect = TRUE) gave an error.
my dbplyr version was 1.4.0. After updating it, the problem was solved !
Is there tool that automatically  searches updates  ;-) ?

**Comment by florisvdh** [comment]
@w-jan , I'm glad that your problem was solved! Just to be sure, does it fix the whole issue or just that example? If OK, you can close the issue.

Keep on signalling things, it is much appreciated and you have an eye for it :-)

**Comment by florisvdh** [comment]
There are several approaches to updating packages. They will update the packages from the repositories that you have set (run `getOption("repos")` to see these). A very good CLI approach is [here](https://inbo.github.io/tutorials/installation/user/user_install_r/#windows), using `update.packages()`. Probably equivalent is RStudio's wizard (Tools -> Check for package updates...).

- Of course, these approaches will not update Github-packages which are not on CRAN and which you manually installed with `remotes::install_github()` (`install_github()` by default takes the _latest_ snapshot on the master branch, not a specific release). To update these, just run the `install_github()` command for these packages again. As a convenience, the command will ask to update package dependencies when updates of these are available, taking into account the repo (CRAN, github, ...) of these packages.
- Your question brings me to the fact that we can actually let `update.packages()` update INBO-packages (such as `inborutils`, `n2khab`, `LSVI`, `watina`, ...) by distributing released package versions into the [INBO drat repository](https://inbo.github.io/drat/), which is listed by `getOption("repos")`. This is convenient to distribute specific releases to users, but it cannot replace the behaviour of `remotes::install_github()` which will install packages from a specific commit.

**Comment by w-jan** [comment]
Thanks Floris 
for the solution and for the tips on how to keep on track :-)
