### ISSUE TITLE
get_xg3(): problem with database-connection

### ISSUE THREAD

**Issue by w-jan** [inbo/watina#61]
When i use get_xg3() the following code produces an error:
`        locs <-
            copy_to(con,
                    locs) %>%
            inner_join(tbl(con, "vwDimMeetpunt") %>%
                          select(loc_wid = .data$MeetpuntWID,
                                 loc_code = .data$MeetpuntCode),
                      .,
                      by = "loc_code")`
Error in result_insert_dataframe(rs@ptr, values, batch_rows) : 
Created a temporary table named: #locs
  nanodbc/nanodbc.cpp:1617: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#locs'.  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared. 

I use following workaround:
`      locs <-
        tbl(con, "vwDimMeetpunt") %>%
        dplyr::select(loc_wid = .data$MeetpuntWID,
               loc_code = .data$MeetpuntCode)`

**Comment by florisvdh** [comment]
What version do you use of `watina`? See `sessioninfo::session_info()`.

See #56 (was included in `0.3.0`, released 20/5).

**Comment by w-jan** [comment]
The current version on my laptop is 0.2.6.9000.
I assume that when i can update (now my current R-version doesn't allow it) this problem is solved.

**Comment by florisvdh** [comment]
See also https://github.com/inbo/n2khab-droogtemeetnet/pull/8#discussion_r450813742 - upgrading `watina` won't work with `install.packages()`. (Cf. [installation instructions](https://inbo.github.io/watina/#installing-testing-and-using-the-watina-package))

**Comment by w-jan** [comment]
With the new released version the problem vanished. Thanks for this !
