### ISSUE TITLE
Use MIT license

### ISSUE THREAD

**Issue by peterdesmet** [inbo/watina#8]
All INBO packages use MIT license. Can this be used for this package as well (currently `GNU General Public License v3.0`)

**Comment by florisvdh** [comment]
Can you explain a bit more of the ways MIT license diverges from GPL? I'm not so familiar with it, but I think it does actually not insist on anything regarding the licensing of derived works. (I do use it for workflow code, e.g. the n2khab-preprocessing repo).

GPL insists on keeping open-source as open-source, it is most often used by FOSS, so it was a deliberate choice :-). BTW, I applied it to the `n2khab` package as well.

Also the `git2rdata` package uses GPL. @ThierryO

If this is contradiction with INBO policy (but is it?), it is to be changed. If not, I tend to keep GPL considering the above.

**Comment by peterdesmet** [comment]
Correct, GPL is a copy left / share-alike license, while MIT is a permissive license. Even though the intentions are good, GPL comes with more conditions than MIT (derivative works need to be open source as well) and as a result might be used less. IMO, as a public instance, INBO should place as few restrictions as possible on its open source software, similar on how we use CC0 for our data.

See https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/

**Comment by florisvdh** [comment]
That's certainly something to think about.

**Comment by peterdesmet** [comment]
Maybe something to discuss within @inbo/bmk, I see you are the only team using GPL-3

**Comment by florisvdh** [comment]
We will discuss this topic.

**Comment by florisvdh** [comment]
Interesting info on open data policy at the Flemish level is [here](https://overheid.vlaanderen.be/voorwaarden-voor-het-hergebruik-van-overheidsinformatie), but it seems that no Flemish policy is yet in place regarding open source code.

**Comment by florisvdh** [comment]
> I see you are the only team using GPL-3

@peterdesmet We discussed this in our team. Apart from the observation that the vast majority of R-packages (and R itself) is GPL, each approach has its pros and cons in advocating the adoption of open science. So it depends on how our institute's vision is on 'advocating/promoting' open science, and ultimately, the government's vision (cf. previous comment).

For now, we propose to leave the choice between MIT and GPL, but only between those two, and leave the choice with the author. If it should be made more stringent, ideally the government should take a position in this.
